services:
  open-webui:
    image: ghcr.io/open-webui/open-webui@sha256:a26effeb220e132482bf7e0560b3404843e7bc40d23051144e062960df8df6b0
    container_name: open-webui
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "3008:8080"

    volumes:
      - ../../data/open-webui:/app/backend/data

    networks:
      - lab-network

networks:
  lab-network:
    external: true
