services:
  litellm:
    image: ghcr.io/berriai/litellm-database:v1.91.1
    container_name: litellm
    restart: unless-stopped

    env_file:
      - .env

    command: ["--config", "/app/config.yaml", "--port", "4000"]

    ports:
      - "4000:4000"

    volumes:
      - ./config/config.yaml:/app/config.yaml

    networks:
      - lab-network

networks:
  lab-network:
    external: true
