services:
  searxng:
    image: searxng/searxng:2026.7.9-8456831a0
    container_name: searxng
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8080:8080"

    volumes:
      - ../../data/searxng:/etc/searxng

    networks:
      - lab-network

networks:
  lab-network:
    external: true
