[options]

; Contraseña maestra para crear, respaldar y restaurar bases
admin_passwd = 346bfad796fa3ef315d5bd117db3f03fd77d694026f460c6a479b9c4091fa2ef

; Base de datos
db_host = postgres
db_port = 5432
db_user = odoo19
db_password = /pI+uLpWezepQI8y78P08IABa/o18Eep

; Directorios
data_dir = /var/lib/odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons

; Red
http_port = 8069
proxy_mode = False

; Desarrollo / laboratorio
list_db = True
without_demo = False

; Logging
log_level = info
logfile = False

; Límites prudentes para el notebook
workers = 0
max_cron_threads = 1
limit_time_cpu = 120
limit_time_real = 240
limit_memory_soft = 1073741824
limit_memory_hard = 1610612736